import { jsPDF } from "jspdf";
import { DiagnosticResponse, ProbableFault, ImmediateAction } from "../types";

export interface PDFReportData {
  plantName: string;
  routeName: string;
  assetName: string;
  componentName: string;
  diagnosticResult: DiagnosticResponse;
  category: "Mechanical" | "Electrical" | "Hydraulic" | string;
  symptoms: string;
}

export function generatePDFReport({
  plantName,
  routeName,
  assetName,
  componentName,
  diagnosticResult,
  category,
  symptoms
}: PDFReportData) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const pageHeight = 297;
  const pageWidth = 210;
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2); // 180mm

  let currentPageNum = 1;

  // Helper to draw border and footer on every page
  const drawPageBorderAndFooter = (pageNum: number) => {
    // Elegant slate grey thin border
    doc.setDrawColor(203, 213, 225); // Slate 300
    doc.setLineWidth(0.3);
    doc.rect(margin - 3, margin - 3, contentWidth + 6, pageHeight - (margin * 2) + 6);

    // Header band on pages > 1
    if (pageNum > 1) {
      doc.setFillColor(15, 23, 42); // Slate 900
      doc.rect(margin - 2, margin - 2, contentWidth + 4, 10, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(255, 255, 255);
      doc.text(`MotorMedic Pro AI • Technical Report • Asset: ${assetName}`, margin + 2, margin + 4.5);
    }

    // Footer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text("Generated by MotorMedic Pro AI • Enterprise Diagnostic System", margin, pageHeight - margin + 4);
    doc.text(`Page ${pageNum}`, pageWidth - margin - 10, pageHeight - margin + 4);
  };

  // Helper to print wrapped text with page overflow handling
  const printWrappedText = (
    text: string,
    x: number,
    y: number,
    maxWidth: number,
    lineHeight: number,
    fontSize: number = 10,
    fontStyle: "normal" | "bold" | "italic" = "normal",
    textColor: [number, number, number] = [30, 41, 59]
  ): number => {
    doc.setFont("helvetica", fontStyle);
    doc.setFontSize(fontSize);
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);

    const lines = doc.splitTextToSize(text || "N/A", maxWidth);
    let curY = y;

    for (let i = 0; i < lines.length; i++) {
      if (curY > pageHeight - margin - 12) {
        currentPageNum++;
        doc.addPage();
        drawPageBorderAndFooter(currentPageNum);
        curY = margin + 15;
        // reset font states since adding a page might reset them in some jsPDF versions
        doc.setFont("helvetica", fontStyle);
        doc.setFontSize(fontSize);
        doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      }
      doc.text(lines[i], x, curY);
      curY += lineHeight;
    }

    return curY;
  };

  // 1. PAGE 1: TITLE BLOCK & LOGO PLACEHOLDER
  drawPageBorderAndFooter(1);

  // Logo Placeholder / Technical Brand Card
  doc.setFillColor(15, 23, 42); // Slate 900 (Dark theme color)
  doc.rect(margin, margin, contentWidth, 32, "F");

  // Logo Graphic
  doc.setDrawColor(234, 179, 8); // Yellow 500
  doc.setLineWidth(1.5);
  doc.line(margin + 10, margin + 10, margin + 10, margin + 22);
  doc.line(margin + 10, margin + 16, margin + 18, margin + 16);
  doc.line(margin + 18, margin + 10, margin + 18, margin + 22);
  // Cross hair/plus in yellow for Medic symbol
  doc.setDrawColor(239, 68, 68); // Red 500
  doc.line(margin + 14, margin + 11, margin + 14, margin + 15);
  doc.line(margin + 12, margin + 13, margin + 16, margin + 13);

  // Title text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text("MOTOR MEDIC PRO", margin + 24, margin + 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(234, 179, 8); // Yellow 500
  doc.text("AI-POWERED CONDITION MONITORING & FAULT DIAGNOSTICS", margin + 24, margin + 24);

  // Subtitle/Metadata date on header banner
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.text(`CONFIDENTIAL ENGINEERING DOCUMENT • ${new Date().toLocaleString()}`, pageWidth - margin - 85, margin + 29);

  let y = margin + 40;

  // Metadata Block: Plant, Route, Asset, Component details
  doc.setFillColor(248, 250, 252); // Slate 50 background
  doc.setDrawColor(226, 232, 240); // Slate 200 border
  doc.setLineWidth(0.5);
  doc.rect(margin, y, contentWidth, 38, "FD");

  // Section Header inside card
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text("I. EQUIPMENT IDENTITY & ANALYSIS CONTEXT", margin + 5, y + 6);
  doc.setDrawColor(203, 213, 225);
  doc.line(margin + 5, y + 8, margin + contentWidth - 5, y + 8);

  // Data Columns
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text("Plant Location:", margin + 5, y + 14);
  doc.text("Route / Area:", margin + 5, y + 20);
  doc.text("Asset Name:", margin + 5, y + 26);
  doc.text("Component Tag:", margin + 5, y + 32);

  doc.text("System Category:", margin + 95, y + 14);
  doc.text("ISO Severity Zone:", margin + 95, y + 20);
  doc.text("Equipment Status:", margin + 95, y + 26);
  doc.text("Analysis Date:", margin + 95, y + 32);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(15, 23, 42); // Slate 900
  doc.text(plantName || "N/A", margin + 32, y + 14);
  doc.text(routeName || "N/A", margin + 32, y + 20);
  doc.text(assetName || "N/A", margin + 32, y + 26);
  doc.text(componentName || "N/A", margin + 32, y + 32);

  doc.text(category || "N/A", margin + 128, y + 14);
  
  // Highlight ISO zone with status color
  const zone = diagnosticResult.iso_severity_zone || "N/A";
  doc.setFont("helvetica", "bold");
  doc.text(zone, margin + 128, y + 20);
  
  const status = diagnosticResult.equipment_status || "N/A";
  let statusColor: [number, number, number] = [30, 41, 59];
  if (status.includes("CRITICAL") || status.includes("FAULT")) {
    statusColor = [239, 68, 68]; // Red
  } else if (status.includes("MINOR") || status.includes("ISSUES")) {
    statusColor = [245, 158, 11]; // Amber
  } else {
    statusColor = [16, 185, 129]; // Emerald
  }
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.text(status, margin + 128, y + 26);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(15, 23, 42);
  doc.text(new Date().toLocaleDateString(), margin + 128, y + 32);

  y += 45;

  // II. EXECUTIVE SUMMARY
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("II. EXECUTIVE SUMMARY", margin, y);
  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(0.6);
  doc.line(margin, y + 2, margin + contentWidth, y + 2);
  y += 7;

  // Severity indicator bar
  const severity = diagnosticResult.manager_summary?.severity || "Low";
  let sevBgColor = [241, 245, 249]; // light gray
  let sevTextColor = [71, 85, 105];
  if (severity === "Critical") {
    sevBgColor = [254, 226, 226]; // light red
    sevTextColor = [220, 38, 38]; // red 600
  } else if (severity === "High") {
    sevBgColor = [255, 251, 235]; // light amber
    sevTextColor = [217, 119, 6]; // amber 600
  } else if (severity === "Medium") {
    sevBgColor = [240, 253, 250]; // light teal
    sevTextColor = [13, 148, 136]; // teal 600
  }
  doc.setFillColor(sevBgColor[0], sevBgColor[1], sevBgColor[2]);
  doc.rect(margin, y, contentWidth, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(sevTextColor[0], sevTextColor[1], sevTextColor[2]);
  doc.text(`ALARM LEVEL: ${severity.toUpperCase()}`, margin + 5, y + 4.8);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text(`Estimated Downtime: ${diagnosticResult.manager_summary?.estimated_downtime || "N/A"}   |   Repair Cost: ${diagnosticResult.manager_summary?.cost_estimate || "N/A"}`, margin + 85, y + 4.8);

  y += 12;

  // Executive Brief description
  const briefText = diagnosticResult.manager_summary?.executive_brief || "No executive summary available.";
  y = printWrappedText(briefText, margin + 2, y, contentWidth - 4, 5.5, 9.5, "normal", [30, 41, 59]);

  // Symptoms statement if provided
  if (symptoms && symptoms.trim()) {
    y += 4;
    y = printWrappedText(`Observed Field Symptoms: ${symptoms}`, margin + 2, y, contentWidth - 4, 5, 8.5, "italic", [100, 116, 139]);
  }

  y += 8;

  // III. FAULT ANALYSIS DETAILS
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("III. PROBABLE FAULTS AND FREQUENCY ANALYTICS", margin, y);
  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(0.6);
  doc.line(margin, y + 2, margin + contentWidth, y + 2);
  y += 8;

  // Table header for faults
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, contentWidth, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text("Diagnosed Fault Name / Category", margin + 3, y + 4.5);
  doc.text("Confidence", margin + 95, y + 4.5);
  doc.text("Probability", margin + 125, y + 4.5);
  doc.text("Severity", margin + 155, y + 4.5);
  y += 10;

  const probableFaults = diagnosticResult.probable_faults || [];
  if (probableFaults.length === 0) {
    y = printWrappedText("No diagnostic faults detected or normal operation verified.", margin + 3, y, contentWidth - 6, 5, 9, "italic");
  } else {
    probableFaults.forEach((fault: ProbableFault) => {
      const name = fault.fault_name || fault.fault || "Unknown Fault";
      const confidence = fault.confidence || "N/A";
      const probability = fault.probability ? `${fault.probability}%` : "N/A";
      const faultText = fault.description || fault.supporting_evidence || "No description provided.";

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(15, 23, 42);
      doc.text(name, margin + 3, y);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      doc.text(confidence, margin + 95, y);
      doc.text(probability, margin + 125, y);
      doc.text(severity, margin + 155, y);
      y += 5.5;

      // Print fault supporting evidence/description wrapped
      y = printWrappedText(`Evidence: ${faultText}`, margin + 6, y, contentWidth - 12, 4.5, 8.5, "normal", [100, 116, 139]);

      if (fault.calculated_frequencies) {
        y = printWrappedText(`Frequencies of Interest: ${fault.calculated_frequencies}`, margin + 6, y, contentWidth - 12, 4.5, 8, "italic", [100, 116, 139]);
      }
      y += 5;
    });
  }

  y += 5;

  // IV. VIBRATION SPECTRA PLACEHOLDER (With vector craft!)
  if (y > 200) {
    currentPageNum++;
    doc.addPage();
    drawPageBorderAndFooter(currentPageNum);
    y = margin + 15;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("IV. RECONSTRUCTED VIBRATION FREQUENCY SPECTRA (FFT)", margin, y);
  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(0.6);
  doc.line(margin, y + 2, margin + contentWidth, y + 2);
  y += 7;

  // Spectrum Container Box
  doc.setFillColor(248, 250, 252); // Light background
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.setLineWidth(0.5);
  doc.rect(margin, y, contentWidth, 42, "FD");

  // Grid lines inside FFT plot
  doc.setDrawColor(241, 245, 249);
  doc.setLineWidth(0.25);
  for (let gridX = margin + 15; gridX < margin + contentWidth - 5; gridX += 20) {
    doc.line(gridX, y + 5, gridX, y + 35);
  }
  for (let gridY = y + 5; gridY < y + 35; gridY += 10) {
    doc.line(margin + 15, gridY, margin + contentWidth - 5, gridY);
  }

  // Draw simulated FFT Spectrum Wave using Vector lines!
  doc.setDrawColor(14, 116, 144); // Teal 700 line for FFT
  doc.setLineWidth(0.4);
  const startX = margin + 15;
  const endX = margin + contentWidth - 10;
  const plotYBaseline = y + 35;
  let prevX = startX;
  let prevY = plotYBaseline;

  // Let's create a deterministic simulated vibration wave with specific peaks based on the severity!
  const numPoints = 180;
  const step = (endX - startX) / numPoints;
  for (let i = 0; i <= numPoints; i++) {
    const curX = startX + (i * step);
    // Base noise
    let noise = Math.sin(i * 0.15) * 1.5 + Math.cos(i * 0.4) * 0.8 + (Math.random() * 0.5);
    // Add distinct peaks (running frequencies, gearmesh, or fault frequencies)
    if (Math.abs(i - 30) < 3) { // 1X RPM running speed
      noise += (4 - Math.abs(i - 30)) * 6;
    }
    if (Math.abs(i - 60) < 2) { // 2X RPM
      noise += (3 - Math.abs(i - 60)) * 4;
    }
    if (severity === "Critical" && Math.abs(i - 115) < 3) { // Outer race bearing defect peak
      noise += (4 - Math.abs(i - 115)) * 9;
    } else if (severity === "High" && Math.abs(i - 115) < 3) {
      noise += (4 - Math.abs(i - 115)) * 5;
    } else {
      // Small fault peak
      if (Math.abs(i - 115) < 2) {
        noise += (3 - Math.abs(i - 115)) * 2;
      }
    }

    const valueHeight = Math.max(0.2, Math.min(28, noise));
    const curY = plotYBaseline - valueHeight;
    
    if (i > 0) {
      doc.line(prevX, prevY, curX, curY);
    }
    prevX = curX;
    prevY = curY;
  }

  // Draw axis lines
  doc.setDrawColor(71, 85, 105); // Slate 600 axis
  doc.setLineWidth(0.6);
  doc.line(startX, y + 4, startX, plotYBaseline); // Y-axis
  doc.line(startX, plotYBaseline, endX, plotYBaseline); // X-axis

  // Axis Labels
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text("Amplitude (in/s Peak)", startX - 12, y + 6, { angle: 90 });
  doc.text("Frequency (Hz / Order)", startX + (contentWidth / 2) - 15, plotYBaseline + 4);

  // Markers
  doc.text("0.0", startX - 7, plotYBaseline);
  doc.text("0.5", startX - 7, plotYBaseline - 10);
  doc.text("1.0", startX - 7, plotYBaseline - 20);
  doc.text("1.5", startX - 7, plotYBaseline - 30);

  doc.text("1X", startX + 30 - 2, plotYBaseline + 3);
  doc.text("2X", startX + 60 - 2, plotYBaseline + 3);
  doc.text("BPFI/BPFO Fault Zone", startX + 115 - 12, plotYBaseline + 3);

  // Title info inside FFT Plot
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text("Digital Condition Waveform FFT Spectral Plot", startX + 5, y + 8);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  doc.text(`Sampling Bandwidth: 2.5 kHz  |  Line Resolution: 1600 Lines  |  Overall Velocity RMS: ${diagnosticResult.overall_vibration_level || "0.24 in/s"}`, startX + 5, y + 12);

  y += 49;

  // V. RECOMMENDED ACTIONS
  if (y > 210) {
    currentPageNum++;
    doc.addPage();
    drawPageBorderAndFooter(currentPageNum);
    y = margin + 15;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("V. RECOMMENDED MAINTENANCE ACTIONS", margin, y);
  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(0.6);
  doc.line(margin, y + 2, margin + contentWidth, y + 2);
  y += 7;

  const actions = diagnosticResult.immediate_actions || [];
  if (actions.length === 0) {
    y = printWrappedText("No immediate maintenance actions recommended. Monitor operation.", margin + 2, y, contentWidth - 4, 5, 9, "italic");
  } else {
    actions.forEach((act: ImmediateAction, idx: number) => {
      const priority = act.priority || "Medium";
      const timeEst = act.timeline || act.estimated_time || "N/A";
      const safety = act.safety_warning ? `\n⚠️ SAFETY: ${act.safety_warning}` : "";

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(15, 23, 42);
      doc.text(`${idx + 1}. [Priority ${priority}] ${act.action}`, margin + 2, y);
      y += 5;

      const detailText = `Estimated Duration: ${timeEst}  |  Required Tools: ${act.required_tools ? act.required_tools.join(", ") : "Standard Hand Tools"}\nRationale: ${act.rationale || "Condition monitoring verification."}${safety}`;
      y = printWrappedText(detailText, margin + 6, y, contentWidth - 12, 4.5, 8.5, "normal", [71, 85, 105]);
      y += 4;
    });
  }

  // VI. ENGINEER SIGN-OFF NOTES
  if (y > 220) {
    currentPageNum++;
    doc.addPage();
    drawPageBorderAndFooter(currentPageNum);
    y = margin + 15;
  }

  y += 5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("VI. ENGINEERING NOTES & SIGN-OFF", margin, y);
  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(0.6);
  doc.line(margin, y + 2, margin + contentWidth, y + 2);
  y += 8;

  // Empty Lines for engineering hand notes
  doc.setDrawColor(203, 213, 225); // Slate 300
  doc.setLineWidth(0.3);
  doc.line(margin + 2, y + 8, margin + contentWidth - 2, y + 8);
  doc.line(margin + 2, y + 16, margin + contentWidth - 2, y + 16);
  
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8.5);
  doc.setTextColor(148, 163, 184);
  doc.text("Write hand-written field observations, lubrication log numbers, or alignment check tolerances above.", margin + 4, y + 4);

  // Signature Blocks
  y += 24;
  doc.setDrawColor(148, 163, 184);
  doc.line(margin + 10, y + 8, margin + 70, y + 8);
  doc.line(margin + 110, y + 8, margin + 170, y + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text("Lead Reliability Engineer Signature", margin + 18, y + 12);
  doc.text("Operations Manager Clearance Signature", margin + 115, y + 12);

  doc.text("Date: ____/____/2026", margin + 10, y + 17);
  doc.text("Date: ____/____/2026", margin + 110, y + 17);

  // Save the PDF
  const filename = `MotorMedic_Pro_Report_${assetName.replace(/[^a-zA-Z0-9]/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}
